<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>
<?php if($SeoDetails['seotitle']!=""){ echo $SeoDetails['seotitle']." | ".FIRM_NAME; }else { echo "Terms and Conditions - " .FIRM_NAME; } ?>
</title>
<meta name="description" content="<?php echo $SeoDetails['seodescription'];?>">
<meta name="keywords" content="<?php echo $SeoDetails['seokeywords'];?>">
<meta name="author" content="KD Bhindi Jewellers">
<meta property="og:title" content="<?php echo $SeoDetails['seotitle'];?> |  KD Bhindi Jewellers" />
<meta property="og:description" content="<?php echo $SeoDetails['seodescription'];?>" />
<?php $this->load->view('common/common_css');?>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<?php $this->load->view('common/common_css.php');?>
</head>
<body>
<header class="header">
  <?php $this->load->view('common/header.php');?>
</header>
<main>
  <!-- Breadcrumb Start -->
  <section class="breadcrumb-section">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="breadcrumb-content">
            <h1 class="page-title">Terms and Conditions</h1>
            <ul class="breadcrumb-page-list">
              <li class="breadcrumb-item"><a href="<?php echo base_url(); ?>">Home</a></li>
              <li class="breadcrumb-item">Terms and Conditions</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Breadcrumb End -->
  <!-- Page Section Content Start -->
  <section class="page-secton-wrapper section-space-ptb">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="privacy-policy-content">
            <h2 class="title fw-bold mb-2">Terms and Conditions</h2>
            <p class="text">Our website address is: https://venusproducts.in</p>
            <p class="text"align="justify">The portal www.venusproducts.in, is managed and operated by Venus Products ("we", "us" or "our"). Any natural or legal person who accesses and/or uses This portal in any manner (“you” or “ your”) or uses any current or future service or functionality or offer made available on venusproducts.in ("Service") will be subject to these terms and conditions for use of venusproducts.in ("Terms of Use"), as updated from time to time and such terms, guidelines and conditions as may be applicable to such Service ("Service Terms"). If these Terms of Use are inconsistent with such Service Terms, the Service Terms will control to the extent of such inconsistency with respect to the applicable Service.</p>
            <p class="text"align="justify">These Terms of Use constitute an electronic record within the meaning of The portal law. This electronic record is generated by a computer system and does not require any physical or digital signatures. Please read these Terms of Use carefully before using or accessing www.venusproducts.in or availing any Service. By using the www.venusproducts.in or availing any services, you signify your agreement to be bound by these Terms of Use.</p>
            <h2 class="fw-bold mb-2">Use of www.venusproducts.in</h2>
            <p class="text" align="justify">You agree and acknowledge that www.venusproducts.in is an online platform that enables you to purchase the products listed on www.venusproducts.in at the indicated price at any time from the serviceable locations. Except where we are the seller of the relevant product on www.venusproducts.in, you agree and acknowledge that we are only a facilitator and are not and cannot be a party to or control in any manner any transactions on www.venusproducts.in. Accordingly, such contract of sale of products on the website shall be a strictly bipartite contract between you and the sellers on www.venusproducts.in.</p>
            <h2 class="fw-bold mb-2">Eligibility</h2>
            <p class="text mb-5" align="justify">Only persons who can enter into legally binding contracts as per Indian Contract Act, 1872, i.e. persons who are 18 years of age or older, are of sound mind, and are not disqualified from entering into contracts by any law, can use and access www.venusproducts.in. If you are a minor i.e. under the age of 18 years, you may use www.venusproducts.in only with the involvement of a parent or guardian. </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Page Section Content End -->
  <!-- Newsletter Start-->
  <?php $this->load->view('common/newsletter.php');?>
  <!-- Newsletter End -->
  <!-- Our Feature Section Start -->
  <?php $this->load->view('common/features.php');?>
  <!-- Our Feature Section End -->
</main>
<?php $this->load->view('common/footer.php');?>
<!--  offcanvas Minicart Start -->
<?php $this->load->view('common/cart.php');?>
<!--  offcanvas Minicart End -->
<!-- Quick View Modal Start -->
<?php $this->load->view('common/quick_view_modal.php');?>
<!-- Login & Register Modal Start -->
<?php $this->load->view('common/login_modal.php');?>
<!-- JS Vendor, Plugins & Activation Script Files -->
<?php $this->load->view('common/footer_js.php');?>
</body>
</html>
